name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "versions/**"
      - ".github/**"
  pull_request:


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
#    # [FEATURE] MIXIN_AUDITOR
#    with:
#      mixin_audit: true
    secrets: inherit
    with:
      mixin_audit: true
