name: _step.matrix_prepare

on:
  workflow_call:
    inputs:
      target_subproject:
        description: see release.yml, for generating matrix entries
        type: string
        required: false
        default: ''
    outputs:
      matrix:
        description: The generated run matrix
        value: ${{ jobs.matrix_prep.outputs.matrix }}


jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - id: setmatrix
        run: python .github/workflows/scripts/matrix.py
        env:
          TARGET_SUBPROJECT: ${{ inputs.target_subproject }}

    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
