name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        required: true


jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: 'Display current branch/tag name'
        run: echo ${{ github.ref_name }}

      - id: setmatrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:
          # inputFile: '.github/workflows/matrix_includes.json' # Default input file path
          filter: '[? `${{ github.event_name }}` == `release` || `${{ github.ref_name }}` == branch]'

      - name: 'Print matrix'
        run: echo ${{ steps.setmatrix.outputs.matrix }}

  release:
    needs: matrix_prep
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
        env:
          BUILD_RELEASE: true

      - name: Find correct JAR  # ty fabric carpet
        id: findjar
        run: |
          output="$(find build/libs/ ! -name "*-dev.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "::set-output name=jarname::$output"

      - name: Upload to action artifact
        uses: actions/upload-artifact@v2
        with:
          name: '[${{ matrix.branch }}] build-artifacts'
          path: build/libs/

      - name: Get github release information
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: get_release
        uses: cardinalby/git-get-release-action@v1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.target_release_tag }}

      - name: Generate publish related infomation
        id: release_info
        # the default value of tag_name is github.ref,  see https://github.com/softprops/action-gh-release#-customizing
        run: |
          if [ $GITHUB_EVENT_NAME == 'release' ]
          then
              echo "::set-output name=tag_name::${{ github.ref }}"
          elif [ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]
          then
              echo "::set-output name=tag_name::${{ github.event.inputs.target_release_tag }}"
          else
              echo Unknown github event name $GITHUB_EVENT_NAME
              exit 1
          fi

      - name: Upload to Github release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/${{ steps.findjar.outputs.jarname }}
          tag_name: ${{ steps.release_info.outputs.tag_name }}

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 397510  # https://www.curseforge.com/minecraft/mc-mods/carpet-tis-addition
          game_endpoint: minecraft
          game_versions: ${{ matrix.cf_game_versions }}
          changelog_type: markdown
          changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}  # one of them should be an empty string (null)
          file_path: build/libs/${{ steps.findjar.outputs.jarname }}
          release_type: release
          relations: carpet:requiredDependency
